### ISSUE TITLE
my normal facebook feeds in my "home" area are blocked in facebook or this facebook adblocker

### ISSUE THREAD

**Issue by walterramjet** [tiratatp/facebook_adblock#13] opened 2018-09-02 00:24 UTC
using Firefox, the facebook adblock is also blocking my normal feeds from groups I am following.  This started last week, i think.  If I use Chrome, facebook works fine so I went to my addons in Firefox and disabled facebook adblock and now my feeds are coming in like normal. I wonder whats going on?
thanks,
Walt

**Comment by yan12125** [comment] 2018-09-02 04:27
Sounds like a duplicate of #12

**Comment by tiratatp** [comment] 2018-09-02 18:15
Duplicate of #12

**Closed by tiratatp** 2018-09-02 18:15 UTC
