### ISSUE TITLE
Doesn't work with "New Facebook" on chrome

### ISSUE THREAD

**Issue by RipTornSideways** [tiratatp/facebook_adblock#67] opened 2020-05-31 17:07 UTC
As the title says, Old facebook look was running like garbage for me(they probably made it run bad to make people switch) so I switched to the new look and I'm getting ads every 2 posts like I used to before installing this. Please update this to work with new FB, I need it.

**Comment by rovingrambler** [comment] 2020-06-16 16:54
I second RipTornSideways; it is no longer working. I use Brave on Debian

**Comment by tiratatp** [comment] 2020-07-20 01:08
It's hard to debug this issue. @cbotsikas is it still working for you in New Facebook?

**Comment by tjk911** [comment] 2020-08-27 22:05
Bump - Facebook forced me onto the new layout and I'm seeing sponsored ads as well.

**Comment by tiratatp** [comment] 2020-09-02 19:14
I still don't have the new Facebook, so I cannot debug this. If someone is willing to code this, and test, I can review and merge

**Comment by tiratatp** [comment] 2020-09-14 15:03
Hey @cbotsikas do you have time to debug this issue?

**Comment by rcvfdmark** [comment] 2020-09-25 17:50
I have seen general "sponsored" ads appear in my feed, only to disappear again on a refresh. One political ad that I looked into didn't contain the [aria-label="Sponsored"] tag that I believe the blocker looks for. I didn't see much in the way of stuff to capture for detection, but the HTML of the FeedUnit is linked below if you think that will help. Once the general sponsored ads show up, I'll grab one for you.

https://pastebin.com/TLnMv8Wq

**Comment by rcvfdmark** [comment] 2020-09-25 18:25
OK here we go! This one does have [aria-label="Sponsored"] so I'm not sure what's up. But here's the html for it. HTH

https://pastebin.com/ec46SXAh

![image](https://user-images.githubusercontent.com/17238805/94302884-2dc7ce80-ff2a-11ea-8fef-bceec6888c8e.png)

**Comment by pa28236** [comment] 2020-10-07 11:14
I'm getting the ads non-stop in the new version of FB. Any idea when this will be corrected and pushed out?

**Comment by TechGuyTN** [comment] 2020-10-08 22:58
Same here on the new Facebook layout.

**Comment by pa28236** [comment] 2020-10-12 14:10
When this is fixed, please include the "Suggested for You" in the fix? I'm getting these non-stop. Thanks, and keep up the great work!

**Comment by littlefico** [comment] 2020-11-10 19:38
i have sponsered links in facebook as of yesterday again.
is there any hope to fix this?

**Comment by tiratatp** [comment] 2020-12-16 19:29
I don't see these myself. This extension does not look for `[aria-label="Sponsored"]` specifically.

**Comment by tiratatp** [comment] 2020-12-16 19:31
I just published 1.8.8 for sidebar ads, can anyone try and report back?

**Comment by pa28236** [comment] 2020-12-16 19:37
How do we get 1.8.8 for Chrome? Currently only 1.8.7 available.

**Comment by tiratatp** [comment] 2020-12-17 01:31
Chrome takes a while to review each new version. Maybe up to a week?

**Comment by tiratatp** [comment] 2020-12-24 20:31
1.8.8 is live on Chrome. I'm going to close this since I cannot reproduce. I also don't believe there is any different between a layout on Firefox and Chrome.

**Closed by tiratatp** 2020-12-24 20:31 UTC
