### ISSUE TITLE
Sponsered Links in Firefox again

### ISSUE THREAD

**Issue by littlefico** [tiratatp/facebook_adblock#73] opened 2020-11-10 19:39 UTC
i have sponsered links in facebook as of yesterday again.
is there any hope to fix this?

**Comment by tartansandal** [comment] 2020-12-01 09:53
Am seeing this too, but only after leaving Facebook open for a while. However, if I refresh the page, the sponsored links are gone. 
I gather the extension is not being triggered when new posts are pushed to an open page.

**Comment by AlesBucek** [comment] 2020-12-03 06:18
(tested on 3rd Dec 2020 with Facebook Adblock 1.8.7. on Firefox 83.0 running on Mac OS Big Sur 11.0.1)

I tried to test this behavior. The extension stopped working for me multiple times after several refreshes or clicks through the FB page but after additional refresh (or several refreshes) the function was restored.

**Comment by TrueCyberAxe** [comment] 2020-12-03 12:18
I am having this issue too.

**Comment by tiratatp** [comment] 2020-12-16 19:27
Where are these ads? I just got a new FB5 today, and I only see sidebar ads. I fixed these in 1.8.8

**Comment by tartansandal** [comment] 2020-12-17 06:26
> Where are these ads? I just got a new FB5 today, and I only see sidebar ads. I fixed these in 1.8.8

I'm seeing sponsored ads in the main feed. Using FF 83 and version 1.8.8.

**Comment by tartansandal** [comment] 2020-12-17 06:43
Ah,  i see they have broken "sponsored" up into individual characters inside <b> tags.  The outer <a> tag still has an aria-label=" Sponsored" though. Should that have been picked up?

**Comment by tiratatp** [comment] 2020-12-24 20:31
I'm going to close this since I cannot reproduce. I also don't believe there is any different between a layout on Firefox and Chrome.

**Closed by tiratatp** 2020-12-24 20:31 UTC

**Comment by tartansandal** [comment] 2020-12-24 23:34
Just submitted a PR that fixes the issue for me on Firefox

**Comment by tiratatp** [comment] 2020-12-25 00:26
Thanks Kal. I published this as 1.8.9
