### ISSUE TITLE
getVisibleText(...).join is not a function

### ISSUE THREAD

**Issue by risototh** [tiratatp/facebook_adblock#46] opened 2020-01-20 23:08 UTC
JS error in console on scroll down, when new posts are loaded into the feed:

> content.js:91 Uncaught TypeError: getVisibleText(...).join is not a function
>     at content.js:91
>     at Array.some (<anonymous>)
>     at content.js:90
>     at Array.some (<anonymous>)
>     at hideIfSponsored (content.js:88)
>     at content.js:115
>     at Array.forEach (<anonymous>)
>     at MutationObserver.<anonymous> (content.js:113)

Issue in this code:

> return possibleSponsoredTextQueries.some(query => {
>       const result = e.querySelectorAll(query);
>       return [...result].some(t => {
>         const visibleText = getVisibleText(t).join("");

**Comment by tiratatp** [comment] 2020-01-25 13:03
Hey Richard. Thanks for reporting the issue. Could you include the version
of your browser and the version of the extension?

**Comment by risototh** [comment] 2020-01-27 07:54
Hi.
Chrome 79.0.3945.88
Extension 1.7.2

**Comment by tiratatp** [comment] 2020-02-11 15:56
Should be fixed in 1.7.3

I think this is caused by some dependencies. I updated them and I cannot reproduce.

**Closed by tiratatp** 2020-02-11 15:56 UTC
