### ISSUE TITLE
sponsored post in search menu

### ISSUE THREAD

**Issue by r3gamerz** [tiratatp/facebook_adblock#97] opened 2021-05-30 09:48 UTC
chrome 90 can see sponsored post in the search
![image](https://user-images.githubusercontent.com/58042048/120099629-c6bc8280-c166-11eb-9625-2c92a65b4435.png)

**Comment by tiratatp** [comment] 2021-06-24 18:30
Probably a duplicate of #95.

Please try again with v1.9.4 and if there is still a problem, please reopen this ticket.

**Closed by tiratatp** 2021-06-24 18:30 UTC
