### ISSUE TITLE
Not blocking anything on Chrome

### ISSUE THREAD

**Issue by pa28236** [tiratatp/facebook_adblock#91] opened 2021-04-14 20:12 UTC
**Environment**
 - Extension version: 1.9.2
 - Browser and version: Chrome   89.0.4389.128
 - OS and version: Windows 10

**Describe the bug**
I'm getting ads almost every other post. I see constant "Sponsored" and "Suggested for You" ads!

**Expected behavior**
I expect to not see these ads!

**Comment by cbotsikas** [comment] 2021-04-16 17:37
Can not reproduce. 

What is your Facebook language?
If you open Console ( Ctrl + Shift + J ) do you see any errors?
If you refresh the main page ( facebook.com ) with your console open, you shall see two messages "Monitoring feed updates" and "Monitoring page changes"

![image](https://user-images.githubusercontent.com/1640100/115062814-0e56ba00-9eeb-11eb-8934-07dcaaac5d1f.png)

**Comment by cbotsikas** [comment] 2021-04-22 14:31
@pa28236 Is this still an issue for you?

**Comment by pa28236** [comment] 2021-04-22 17:42
Yes, this is still a problem for me. Doing what you state, I see a lot of error messages in red.

![image](https://user-images.githubusercontent.com/61201326/115761572-79334580-a370-11eb-9412-16e549abaf1f.png)

**Comment by pa28236** [comment] 2021-04-23 19:45
Every other post is an advertisement. Getting tired of looking at this crap.

**Comment by cbotsikas** [comment] 2021-04-23 21:28
@pa28236 the errors you see there are caused by McAfee WebAdvisor, based on the id I see on your screenshot ([fheoggkfdfchfphceeifdbepaooicaho](https://chrome.google.com/webstore/detail/mcafee%C2%AE-webadvisor/fheoggkfdfchfphceeifdbepaooicaho?hl=en)).
Can you try again after you have disabled it from chrome?

**Comment by cbotsikas** [comment] 2021-04-23 21:29
Can you also please share a screenshot of an ad? What language do you use on Facebook?

**Comment by VikingJan** [comment] 2021-04-24 09:30
![image](https://user-images.githubusercontent.com/83116372/115954262-eddcc000-a4e7-11eb-9c93-936ccd27cab4.png)
Having the same issue. 
I use English on Facebook. Ad and console in screenshot.

**Comment by cbotsikas** [comment] 2021-04-24 09:47
@VikingJan your issue is different and was fixed and released today with v1.9.3. Firefox plugin is already updated. For Chrome, it's being reviewed by Google and should be available to you within a couple of days.

**Comment by VikingJan** [comment] 2021-04-24 10:47
> @VikingJan your issue is different and was fixed and released today with v1.9.3. Firefox plugin is already updated. For Chrome, it's being reviewed by Google and should be available to you within a couple of days.

Ah right, will check again in a few days then. Thanks!

**Comment by pa28236** [comment] 2021-04-26 14:00
It looks like I'm now running version 1.9.3 and it's working again. When it was 1.9.2, I was getting the ads like crazy.
Is there anyway to get rid of the "Suggested for You" ads? Even having a toggle switch in the settings to remove these, for those that want to, would be awesome. I get a lot of these and they're super annoying.
![image](https://user-images.githubusercontent.com/61201326/116095292-4641c800-a676-11eb-911f-7ae21fe73599.png)

**Comment by cbotsikas** [comment] 2021-04-26 14:08
I'm glad the update fixed your issue too. I'm closing this ticket since we already have an open task #62 for adding support to block "suggested for you" posts

**Closed by cbotsikas** 2021-04-26 14:08 UTC
Labels: bug
