### ISSUE TITLE
Facebook Ad Blocker no longer works

### ISSUE THREAD

**Issue by dlathem** [tiratatp/facebook_adblock#51] opened 2020-04-07 14:53 UTC
This morning my WIN 10 Facebook page began flashing timeline content....the page could not be used.  I disabled the Facebook AD blocker and that solved the problem.  I re-installed the Ad Blocker and the problem came back.  So, apparently Facebook has figured out how to make your great ad blocker ineffective.  I have uninstalled it again and my FB page is back to normal.

**Comment by cbotsikas** [comment] 2020-04-07 14:56
hi @dlathem yes, you are correct. facebook did change some code today. It's already tracked with issue https://github.com/tiratatp/facebook_adblock/issues/50 and hopefully fixed ASAP. Sorry about that. I feel bad because the code that no longer works was mine...

**Comment by dlathem** [comment] 2020-04-07 15:00
OK...I can no longer find the extension on line.  Have you pulled it down?  I saw your post after I posted mine and saw where you talked of a patch so Installed it again with the same result.  Now an extension search turns up nothing.  Thanks for this extension.

**Comment by cbotsikas** [comment] 2020-04-07 15:07
No, the extension is still up. You can find it on the following link: https://chrome.google.com/webstore/detail/ad-blocker-for-facebook/kinpgphmiekapnpbmobneleaiemkefag

All credits for this extension goes to the author @tiratatp. I can only take the blame for the latest aggressive rule that broke your feed.. I have the fix ready but the author needs to accept it and push the update to the store..

**Comment by tiratatp** [comment] 2020-04-07 15:39
Hey @cbotsikas thanks for fixing this so fast. Yeah I think what you see if a duplicate of #52 

This should be fixed in 1.7.6 for Chrome. For Firefox you are unaffected.

**Closed by tiratatp** 2020-04-07 15:39 UTC

**Comment by cbotsikas** [comment] 2020-04-07 15:59
@dlathem I've tested the latest available version (1.7.6) from the store and works ok now.
